---
title: "TeamProject_week7_CB"
author: "CHAEBEOM"
date: "2022-08-08"
output: html_document
---

### < 자전거 대여 수요에 대한 예측 >
#### 목적 : 자전거를 임대하는 수단인 '자전거 공유 시스템'의 대여 정확한 수요 예측  


####  1. 파일 로딩
```{r}
library('readxl')
bikeTr <- read.csv('./bike/train.csv', header = 1)
head(bikeTr)
# 일부 출력물 확인

```

####  2. 변수 유형 및 특성
```{r}
str(bikeTr)
# 데이터 프레임 확인
```

1) 관측값 vs. 변수  

- 관측값 : 10886개
- 변수 : 12개
 -> 변수가 많은 데이터셋은 그것대로 고민, 적어도 적은대로 고민
 -> 해당 데이터셋의 
 
2) 범주형 vs. 수치형  

- 범주형 변수 : 5개 (datetime, season, holiday, workingday, weather)  
 -> datetime은 [ 연/월/일/시각 ]으로 떼어 생각한다고 생각하여 범주로 생각  
 -> 나머지는 각각 계절, 휴일/근무일 여부, 날씨 등으로 구분할 수 있다고 생각  
- 수치형 변수 : 7개 (나머지)  
 -> train 데이터셋에서는 매월 1-19일까지 자료밖에 없음
 -> 

3) 종속변수 vs. 독립변수  

- 종속변수 : 1개(count)  
- 독립변수 : 나머지

---------------------------------------------------------------
(1) 수치형 변수 (numeric)  
- bill_length_mm          : 부리의 길이  
- bill_depth_mm           : 부리의 깊이  
- flipper_length_mm       : 날개의 길이  
- body_mass_g             : 체중  
- year                    : 연구연도(07,08,09)  
  
(2) 범주형 변수 (categorial)  
- species          : 종 (Adelie , Chinstrap, Gentoo)  
- island           : 섬 서식지 (Biscoe, Dream, Torgersen)  
- sex              : 성별 (female, male)  
---------------------------------------------------------------
